### ISSUE TITLE
Pixel Framework does not work if your phone's overlay folder is /product/overlay

### ISSUE THREAD

**Issue by danieldeng2** [Magisk-Modules-Repo/Pix3lify#102]
manually copying the files to the folder crashes settings when opening "apps and suggestions".

**Comment by danieldeng2** [comment]
Also my phone keeps asking me for my pin for extra security.

**Comment by lzlrd** [comment]
When I'm free I'll check if Magisk supports this and implement it.

**Comment by danieldeng2** [comment]
> When I'm free I'll check if Magisk supports this and implement it.

Thank you so much. I think quick switch has a working implementation if you want an existing example. Could you update this thread when the bug is solved? thanks again.
