### ISSUE TITLE
Bootloop on uninstall

### ISSUE THREAD

**Issue by aravindvnair99** [Magisk-Modules-Repo/Pix3lify#2]
**Story:**

I have a [Motorola Moto G4 Play XT1602 harpia](https://www.gsmarena.com/motorola_moto_g4_play-8104.php#xt1602) running [Pixel Experience Pie with the latest updates](https://download.pixelexperience.org/harpia/). I also have Magisk installed. Any module I install, I am able to uninstall safely except Pix3lify. I have wiped the phone so many times in an attempt to find the right way to uninstall, but no matter which method I try, it always ends up in a bootloop.

**Expected Outcome:**

1. Install OS.
2. Install Magisk ZIP.
3. Install Magisk Manager APK.
4. Install Pix3lify through Magisk Manager.
5. Uninstall Pix3lify through Magisk Manager.
6. Reboot back into OS automatically.
7. Continue using OS.

**Actual Outcome**

Until step 6, everything is as expected. Step 7 doesn't happen as it just goes into a bootloop.

**Trials**

1. I have tried different versions of Magisk Manager APK and Magisk Installer ZIP.
2. I have tried clearing cache and dalvik cache after each step.
3. I have tried uninstalling using [uninmod](https://forum.xda-developers.com/showpost.php?p=72542167&postcount=242)
4. I have tried dirty flashing OS.
5. I have tried restoring stock boot image.
6. I have tried uninstalling Magisk.
7. I have tried reinstalling Magisk.

**What works?**

Wiping storage and reinstalling OS and everything completely which is ridiculous to do each time. (Apologies if that sounds rude, no such intentions. I'm just frustrated after trying endlessly for last 4 days and having wiped my phone 46 times now to be precise.)

**FAQ**

1. Why do I still want Pix3lify even after installing Pixel Experience?

Because the OS currently doesn't have night light and gesture settings. Everything else is available and Pix3lify has had great development from start.

2. Have I tried the separate Gesture Settings module which you have made?

Yes, it works great. Thanks a ton! 😊 But I couldn't find night light which is why I still install Pix3lify.

3. Why do I want to uninstall Pix3lify?

Because I'm quite sure the project maintainer of Pixel Experience for my OS will implement Gesture Settings and Night Light, but it seems to be taking long to send out updates. The OS is still being made. Everything else works and is amazing. Fluid and responsive.

**Additional bugs**

Wave to wake and wave to glance doesn't work. I think the proximity sensor isn't used correctly as these two features require the proximity sensor. It gets stuck trying to turn the screen on. And all other gestures stop working after which I should turn on the screen and turn it off for other gestures to start working again. But again, proximity sensor gestures don't work in either Pix3lify or Gesture Settings on my device. Ambient Display and pick up to glance works perfectly. No issues. Although sometimes the vibrations misfire. But it's still manageable.

@joeyhuab and @topjohnwu please look into this. I'm willing to test on my device. Looking forward to a response.

**Comment by aravindvnair99** [comment]
Few things I left out:

Uninstalling or disabling Pix3lify from Magisk Manager has same effect on my device.

**Suggestions**

I feel it would be nice to have let the users pick what they want when installing using the volume up and down buttons. I have seen a lot of modules implement this feature and it works great. That way, only what is necessary is installed. I feel this is good because I feel the uninstaller isn't completely removing all components and it would be a nice option to let users pick. Also, I have Pixel 3 Wallpapers builtin. But Pix3lify seems to remove them completely with no other changes when installing. I don't know about uninstalling or disabling Pix3lify as I just end up in a bootloop always irrespective of which method I try.

**Comment by joeyhuab** [comment]
Module removed from the repo.
