### ISSUE TITLE
I can't use the Call screening feature

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Pix3lify#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Essential PH-1]
 - Android Version: [e.g. Android 9.0 December Build]
 - ROM: [e.g. stock]
 - Module Version [e.g. 2.2.0]

**Logs**
Add logs to give context

**Additional context**

**Comment by thehappydinoa** [comment]
Would you please use the [bug report issue](https://github.com/Magisk-Modules-Repo/Pix3lify/issues/new?assignees=&labels=bug&template=bug_report.md&title=) format as this does not give me enough information.

**Comment by ThatNerdyPikachu** [comment]
@rap4ytm I've edited your issue to include the bug report template. Please fill in the fields.

Thanks!
