### ISSUE TITLE
I can't use the call screening feature

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Pix3lify#28]
The bug is that I can't use the call screening feature

1. Go to Google dialer
2. Click on the Tag points
3. Click on settings
4. Can't See the feature

I Had thougt that I can see the feature

 - Device: Google Pixel 2
 - Android Version: Android 9.0 October Build
 - Module Version: 2.2.

The name of the file who I downloaded is : com.google.android.dialer_27.0.225573798-publicbeta-3347325_minAPI24(arm64-v8a)(240dpi)_apkmirror.com (1).apk

Nobody in the pix3lify Support Channel in Telegramm can help me.

**Comment by thehappydinoa** [comment]
Hi, I think I see the problem, I believe you need to be on at least the December build. WOuld you consider upgrading?

**Comment by ghost** [comment]
I can't upadte to the December build because it don't show me the update If I'm looking for it. Normaly I have to restore the images in Magisk and than it works. But I don't have an original backup and that's the reaseon why I can't upadte my device .

**Comment by thehappydinoa** [comment]
Ya I ran into some issues with that too, I found the images for the pixel 2: https://developers.google.com/android/images for the moment call screening only works on December build.

**Comment by ghost** [comment]
Thanks youso much. I will try this. Wegen it works I would tell it to u

**Comment by thehappydinoa** [comment]
Ok sounds good

**Comment by thehappydinoa** [comment]
So quick question, does your Pixel 2 not bootloop after you install our module like #32?

**Comment by ghost** [comment]
Well I didn't Had Install the December upadte yet because I would to Install the Januray upadate as soon as possible

**Comment by thehappydinoa** [comment]
Ok and also Call Screening I believe has been pushed to most Pixel devices. I am going to close this issue.
