### ISSUE TITLE
Google Ambient Display

### ISSUE THREAD

**Issue by robbins** [Magisk-Modules-Repo/Pix3lify#3]
Installing this module adds ambient display from Pixel on my OnePlus 6T but it's broken - is there a way to have this module but not have ambient display replaced? Do any older versions not have it?

**Comment by joeyhuab** [comment]
Will have to merge this with the other issue. Please refer here instead: https://github.com/Magisk-Modules-Repo/Pix3lify/issues/4 Thanks!
