### ISSUE TITLE
No call screen option

### ISSUE THREAD

**Issue by Ellis2525** [Magisk-Modules-Repo/Pix3lify#34]
Whenever there is an incoming call, I can only choose between answer and decline.

OnePlus 5T 9.0 Pie
December Update
Latest Phone version from APKmirror

**Comment by thehappydinoa** [comment]
Hi please try updating to at least version 2.3.1 as it fixes issues with Google Dialer, also you must reboot for it to take effect **after installing** Google Dialer.

PS - Screening may only affect non-saved numbers (ie. not in your contacts).

**Comment by lazerl0rd** [comment]
Try rebooting your device. Also permissions fix coming in a commit real soon.

**Comment by lzlrd** [comment]
Merged with 
https://github.com/Magisk-Modules-Repo/Pix3lify/issues/33.
