### ISSUE TITLE
Bootloop on OOS oneplus 3t

### ISSUE THREAD

**Issue by accayman7** [Magisk-Modules-Repo/Pix3lify#39]
The module is successfully installed but the first boot takes a while with some lag in the boot animation, then it automatically rebooted.

**Comment by JohnFawkes** [comment]
> The module is successfully installed but the first boot takes a while with some lag in the boot animation, then it automatically rebooted.

have any previous versions worked?

**Comment by accayman7** [comment]
Nope,
The previous one wasn't even successfully installed
I got this,
Pix3lify is only for non pixel devices
Installation failed

**Comment by lzlrd** [comment]
@accayman7 you are using a Pixel spoofing mod. It's changed your build.prop to a Pixel's one.

**Comment by JohnFawkes** [comment]
> @accayman7 you are using a Pixel spoofing mod. It's changed your build.prop to a Pixel's one.

no. read his first post. this one is due to the previous commit i made where i forgot to add the $ for the variables

**Comment by JohnFawkes** [comment]
> Nope,
> The previous one wasn't even successfully installed
> I got this,
> Pix3lify is only for non pixel devices
> Installation failed

if you can grab some adb logs go ahead and do that

**Comment by lzlrd** [comment]
> 
> 
> > @accayman7 you are using a Pixel spoofing mod. It's changed your build.prop to a Pixel's one.
> 
> no. read his first post. this one is due to the previous commit i made where i forgot to add the $ for the variables

Ah cool. @accayman7 sorry about that.

**Comment by thehappydinoa** [comment]
Warning added in 61a2d28
