### ISSUE TITLE
Optional Overlay

### ISSUE THREAD

**Issue by papuruth** [Magisk-Modules-Repo/Pix3lify#4]
How to skip the overlay as i dont need it

**Comment by thehappydinoa** [comment]
This could probably be included in the install menu

**Comment by ThatNerdyPikachu** [comment]
@thehappydinoa Could it though?

**Comment by thehappydinoa** [comment]
@ThatNerdyPikachu Yes, we could just edit the props file before rebooting.

**Comment by ThatNerdyPikachu** [comment]
@thehappydinoa Ah, the overlay is through the prop.

**Comment by thehappydinoa** [comment]
@ThatNerdyPikachu Yup, its similar to how we did the launchers.

**Comment by ThatNerdyPikachu** [comment]
@thehappydinoa When did we do that with the launchers? You mean copying the file?

**Comment by thehappydinoa** [comment]
I'll make the function here in a minute
