### ISSUE TITLE
Logs after a bootloop

### ISSUE THREAD

**Issue by Levelleor** [Magisk-Modules-Repo/Pix3lify#54]
**Describe the bug**
Redmi Note 5 (whyred), installed the mod from Magisk app with 1 click, version Pix3lify-v2.4.2.zip. It got in a bootloop after that. For prompts, during the installation process, I answered "yes" to both.

**Smartphone (please complete the following information):**
 - Redmi Note 5 (whyred)
 - Android Version: 8.1.0
 - ROM: stock MIUI Global 10.0
 - Module 2.4.2
 - Magisk: v18.0

**Logs**
[Pix3lify-debug.log](https://github.com/Magisk-Modules-Repo/Pix3lify/files/2723108/Pix3lify-debug.log)

**Additional context**
You asked for logs. I accidentally found them when was preparing my phone for switching to another ROM. I hope they'll help you! :D

**Comment by JohnFawkes** [comment]
these are from the uninstall. install again then without rebooting send the logs again from internal storage then uninstall again before rebooting

**Comment by lzlrd** [comment]
Try with latest version @Levelleor.

**Comment by lzlrd** [comment]
Due to wrong logs and big changes this is closed.
