### ISSUE TITLE
Weather on Lock Screen

### ISSUE THREAD

**Issue by thehappydinoa** [Magisk-Modules-Repo/Pix3lify#61]
**Describe the feature you'd like**

> I've used your mod for a while now and I noticed a feature on the Pixel phones which is showing the weather on the lock screen. Is there any way you can port that feature? - Milan P.

**Links**
[XDA](https://forum.xda-developers.com/showpost.php?p=78593143&postcount=1297)

**Comment by JohnFawkes** [comment]
> **Describe the feature you'd like**
> 
> > I've used your mod for a while now and I noticed a feature on the Pixel phones which is showing the weather on the lock screen. Is there any way you can port that feature? - Milan P.
> 
> **Links**
> [XDA](https://forum.xda-developers.com/showpost.php?p=78593143&postcount=1297)

we could look into it. would need the firmware and just go through it to see what files it is

**Comment by lzlrd** [comment]
@JohnFawkes pretty sure this is SysUI stuff. Practically unportable universally :(. @Stallix can confirm this for us?

**Comment by thehappydinoa** [comment]
Yup just confirmed, will be quite hard as it uses Pixel Ambient Services.

**Comment by MarcAnt01** [comment]
https://github.com/omnirom/android_packages_services_OmniJaws

**Comment by MarcAnt01** [comment]
It's not Google one, but still a reasonable choice

**Comment by lzlrd** [comment]
I guess we can safely close this issue then, modifying SysUIs is unreasonable.
