### ISSUE TITLE
Product Sans font is not enabled

### ISSUE THREAD

**Issue by anton0kurilov** [Magisk-Modules-Repo/Pix3lify#63]
The module use Product (Google) Sans font for headers and some another places. But on my device the font is set as Roboto. More lighter than stock font.

**Smartphone:**
 - Device: OnePlus 3T
 - Android Version: Android 9.0 Pie December Build
 - ROM: Nitrogen OS (23.12.2018)
 - Module Version 2.5.2

**Comment by thehappydinoa** [comment]
This will be fixed in #65

**Comment by thehappydinoa** [comment]
This has been fixed in 2.8
