### ISSUE TITLE
Installing straight away without installing options

### ISSUE THREAD

**Issue by churchner420** [Magisk-Modules-Repo/Pix3lify#69]
When installing v2.6 the installation just runs throught with slim mode and bootanimation without any choosing options...

**To Reproduce**
1. Go to Magisk
2. Installing 2.6
3. See error

**Smartphone (please complete the following information):**
 - Device:Sony Xperia XZ2
 - Android Version: Android 9.0 January Updates
 - ROM: Sony Stock
 - Module Version: 2.6

**Comment by thehappydinoa** [comment]
Hi, thank you for reporting this. We are aware of this issue and will be pushing a fix later today. We believe it is an issue with our keycheco function. Thank you for your patience.

**Comment by thehappydinoa** [comment]
This has been fixed in 2.8
