### ISSUE TITLE
Pixel launcher force closes, Pix3lify 2.0

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Pix3lify#7]
Hey,

Very thankful for your work, best way to get Pix3l experience in one module.

_Problem_: Since 2.0, pixel launcher force closes. "App keeps stopping".
_Device_: Essential PH-1, Android version .099, December security patch (latest).
_Modifications_: Magisk 18.1-021..031 (latest from ianmacd), Ex Kernel 3.11.
_Solutions tried_: Reflashing module doesn't help. Removing all other modules and flashing only Pix3lify, doesn't work. All permissions given to Pixel Launcher.
Call screening, markup works without any problems.

Attaching logcat. It's from 2.0, but same behavior persisted on 2.0.2 as well.
[alogcat.2018-12-11-08-28-48+0200.txt](https://github.com/Magisk-Modules-Repo/Pix3lify/files/2677673/alogcat.2018-12-11-08-28-48%2B0200.txt)

Thanks, if possible, for your help.

**Comment by joeyhuab** [comment]
Please install Pixel Launcher normally from the Play Store or via APKMirror instead. Thanks!
