### ISSUE TITLE
Module installs incompatible apps in Oreo

### ISSUE THREAD

**Issue by JarlPenguin** [Magisk-Modules-Repo/Pix3lify#78]
**Describe the bug**
The module fails to install compatible apps made for Android Oreo. This affects the Wallpapers and Markup app.

**To Reproduce**
1. Install the module and reboot.
2. Open the Wallpapers app/Markup app.
3. See that it crashes.

**Expected behavior**
The module installs apps compatible with Oreo.

**Smartphone (please complete the following information):**
 - Device: Moto G5S XT1794
 - Android Version: Android 8.1 October patch 2018-10-01
 - ROM: Stock
 - Module Version: 2.9

**Comment by thehappydinoa** [comment]
Which exact applications are you talking about?

**Comment by lzlrd** [comment]
@thehappydinoa seems he meant Wallpapers and Markup.

Will if we're using the official Markup then that's understandable (it's only Pie) but Wallpapers gets updated by Play Store for everyone so...

@JarlPenguin give Wallpaper permissions for Storage then update from Play Store and try use it again. If not working still, try use it from a different launcher.

**Comment by JarlPenguin** [comment]
@lazerl0rd 

Wallpapers crashes no matter what I do. It seems that the 9-x  version is for Pie only, while the Play Store version (1.3.x) is for Android 4.1+.

As for Markup, there is a modded version for Oreo on XDA.

**Comment by paskevic** [comment]
same problem here on nexus 6p 8.1.0 - wrong wallpapers app gets installed and it keeps crashing.

**Comment by lzlrd** [comment]
@paskevic @JarlPenguin weirdly I just tried Pix3lify on my Nexus 5X (bullhead) for 8.1 and Wallpapers works fine...

I'll take a look at sorting Markup tho, I've used the Oreo port previously and can get that implemented.

**Comment by lzlrd** [comment]
Fixed in https://github.com/Magisk-Modules-Repo/Pix3lify/pull/76/commits/eb1d06366b04a167907c0d96ab944d561c06a521.
