### ISSUE TITLE
Fonts not applying on Samsung devices

### ISSUE THREAD

**Issue by kaebiene** [Magisk-Modules-Repo/Pix3lify#80]
**Describe the bug**
On Samsung devices, the font files for lockscreen/header/etc are different from standard Roboto fonts - so the module doesn't have an effect on the fonts across the system (seemingly).

**To Reproduce**
Install the module, reboot.

**Expected behavior**
The fonts change system-wide, especially the clock.

**Smartphone (please complete the following information):**
 - Device: Samsung S8 SM-G950F
 - Android Version: 9.0
 - ROM: One UI
 - Module Version: v2.9

**Additional context**
I can provide a list of the fonts required/present in the /system/fonts folder if needed? Otherwise, no worries!

**Comment by lzlrd** [comment]
We need to edit the fonts.xml and also the in-coming update helps out too.

**Comment by lazerl0rd** [comment]
Also lock screen clock will not be changed, that requires editing/overlaying SystemUI and since all SysUIs are different we cannot.

**Comment by lzlrd** [comment]
@kaebiene I just fixed it for many other devices, but can you provide your fonts.xml file from /system/etc?

**Comment by lzlrd** [comment]
Most devices that use Roboto will have the fonts working with this edit -> https://github.com/Magisk-Modules-Repo/Pix3lify/pull/76/commits/eb1d06366b04a167907c0d96ab944d561c06a521.

**Comment by kaebiene** [comment]
Of course, here's the fonts.xml. 

Are you sure about needing to edit SystemUI? At least on Samsung devices, there's ttfs for the clock font, split by android version/year, and replacing those seem to affect the lockscreen. 
You'll see in the xml, but for 9.0, it's just Clock2019L.ttf. 
No worries if that would require too much tweaking.

[fonts.xml.zip](https://github.com/Magisk-Modules-Repo/Pix3lify/files/2973883/fonts.xml.zip)

**Comment by lzlrd** [comment]
Ah, interesting. Well then we could replace those. In AOSP/most other OEMs they need SystemUI edits to change it or force replacing fonts (which isn't recommended).

I may be mixing this up with something else however, but I'll Clock2019L.tff to the files that will be replaced.

**Comment by lzlrd** [comment]
https://github.com/Magisk-Modules-Repo/Pix3lify/pull/76/commits/7b5dee9f56983fa723f691d65e87839136661eb8 fixed here

**Comment by kaebiene** [comment]
Brilliant! It's a shame it's so complicated on AOSP, but at least there is this small victory.

I'll test it out and report when the new version's been released.

**Comment by lzlrd** [comment]
@kaebiene we tried but Product Sans wasn’t working as Clock for many ppl. I think there *was* a fix but I’ll need to try remember it.

**Comment by lazerl0rd** [comment]
Samsung using Clock* for other stuff than LockScreen is kinda a down on their side, so this has been changed from bug to enahancement.

**Comment by lzlrd** [comment]
Fixed https://github.com/Magisk-Modules-Repo/Pix3lify/commit/083d5815f1f92cfdb8842665b4ce032b299b6bc7. Try latest version @kaebiene.

**Comment by kaebiene** [comment]
Yup, works now, thanks! All required fonts are replaced.

**Comment by lzlrd** [comment]
:D
