### ISSUE TITLE
Lockscreen Clock is Messed Up!

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Pix3lify#81]
![Screenshot_20190321-120724](https://user-images.githubusercontent.com/41812694/54728452-1475f180-4bd2-11e9-852f-575c09699075.png)

Hi,

The lockscreen font is Messed Up with your latest version.

Nokia 6.1 (2018) Feb 19 Patch

**Comment by ghost** [comment]
Also many fonts are missing or incorrect.

**Comment by lzlrd** [comment]
Hmm, okay @Slats2 I notice that too, seems the Sammy Clock replacement didn’t work.

**Comment by lzlrd** [comment]
I’ll fix it soon.

**Comment by lzlrd** [comment]
> Also many fonts are missing or incorrect.

This won’t be fixed tho, if you replace with Product Sans many symbols don’t process and we can’t be in charge of that.

**Comment by lzlrd** [comment]
Fixed in 
https://github.com/Magisk-Modules-Repo/Pix3lify/commit/f5298f872f28d85d1aa274bd544758726f38cbac.

**Comment by lzlrd** [comment]
Should work now with Product Sans font @Slats2 https://github.com/Magisk-Modules-Repo/Pix3lify/commit/083d5815f1f92cfdb8842665b4ce032b299b6bc7.
