### ISSUE TITLE
Lockscreen still not working

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/Pix3lify#82]
![Screenshot_20190322-104009](https://user-images.githubusercontent.com/41812694/54791687-15b92400-4c8f-11e9-9fa9-6eed5ad1fef9.png)

Lockscreen font still not working after latest update.

Nokia 6.1 (2018) Feb 19 Patch
Magisk 18.2 Canary

**Comment by lzlrd** [comment]
Yeah so as I mentioned in the group, your OEM's LockScreen uses the "default" font and therefore cannot use the FONT option. Disable it when installing.

**Comment by lzlrd** [comment]
This (https://github.com/Magisk-Modules-Repo/Pix3lify/commit/be593c4125a990aed6a94f5887c1bdf801f355b1) will try add Product Sans like the Pixel has (not everywhere) when FONT replace option isn't being used.
