### ISSUE TITLE
Can you please for God's sake stop messing with the lockscreen clock font

### ISSUE THREAD

**Issue by avarayr** [Magisk-Modules-Repo/Pix3lify#83]
No one wants the lockscreen font replaced. Rollback pls.
Running 2.9.5

![Alt](https://i.imgur.com/p9Kxful.jpg)

**Comment by lzlrd** [comment]
It is reverted, read the new README.md and don't use fonts replacement option.

**Comment by lzlrd** [comment]
I could say can you please for God sake read the installation option. Fonts are now included by default even with FONT option you enable in install. If you check it, it says "replacement" now @avarayr.
