### ISSUE TITLE
Cannot install Pixel framework and/or accents after disabling product sans in the installer.

### ISSUE THREAD

**Issue by kewlduda** [Magisk-Modules-Repo/Pix3lify#84]
During install, after disabling slim mode and product sans font, there is no option to enable the pixel framework or accent.

Logs (pastebin because I'm on mobile) https://pastebin.com/m5Qj8SFc

**Comment by lzlrd** [comment]
@JohnFawkes can you help me out here?

@caleb39411 thanks for the report.

**Comment by JohnFawkes** [comment]
@lazerl0rd I'll fix this when I get off work

**Comment by lzlrd** [comment]
@johnfawkes it's fixed I believe.
