### ISSUE TITLE
Lock screen: Retangle instead of ":"

### ISSUE THREAD

**Issue by JohnGLFour** [Magisk-Modules-Repo/Pix3lify#86]
Title is self explainitory, appears from v2.9.6. Fonts enabled.
Here is the photo: https://imgur.com/a/WeYPJfl

**Comment by lzlrd** [comment]
Again, disable fonts replacement during install.

I've said it so many times, in changelog too now. It'll still add the fonts so apps and ROM can still use but doesn't replace.
