### ISSUE TITLE
Call Screening Issue

### ISSUE THREAD

**Issue by sakifx9** [Magisk-Modules-Repo/Pix3lify#91]
**Describe the bug**
Call screening feature not appearing, changed language reinstalled module followed the steps, step by step on the wiki, still not working 

**Screenshots**

**Device Info:**
 - Device: Pocophone F1
 - Android Version: [ Android 9 April 14 ]
 - ROM: [Resurrection Remix ]
 - Country: [AUS]
 - Carrier: [Vodafone]
 - Phone App Version: [31.0.241960258-publicbeta]

**Functionality:**
 - Is the setting available under phone settings: [No]
 - Have you tried everything in the wiki: [Yes]

**Additional context**

**Comment by lzlrd** [comment]
Please don't replicate issues and add to them instead. Look here https://github.com/Magisk-Modules-Repo/Pix3lify/issues/33.
