### ISSUE TITLE
Uninstalling it led to bootloop

### ISSUE THREAD

**Issue by imagh** [Magisk-Modules-Repo/Pix3lify#93]
Uninstalling the module from magisk led to bootloop.  My device Mi A2 with Android 9 Pie was rooted using Magisk.

Steps to reproduce-
1. Goto Modules in Magisk.
2. Click on the bin button to uninstall pix3lify.
3. Reboot device.
4. Device goes to bootloop.

**Comment by Crescendo-BLYAT** [comment]
I think you never read the instructions.

You MUST uninstall it using the module zip via TWRP, not via Magisk.

**Comment by lzlrd** [comment]
@Crescendo-BLYAT thank you. @iamakashgh read above please and try reinstall then uninstall.
