### ISSUE TITLE
Call Screening Issue

### ISSUE THREAD

**Issue by androidacy-user** [Magisk-Modules-Repo/Pix3lify#97]
**Describe the bug**
Call screening does not have any effect

**Device Info:**
 - Device: Moto z3 play 
 - Android Version: 9.0, May 2019 build
 - ROM: Resurrection remix 7.0.2
 - Country: US
 - Carrier: Verizon 
 - Phone App Version: 34.0.250627521-publicbeta

**Functionality:**
 - How much works: none
 - Is the setting available under phone settings: No
 - Have you tried everything in the wiki: followed directions exactly, minus opting into beta because I was already in

**Additional context**

**Comment by lzlrd** [comment]
Replica of https://github.com/Magisk-Modules-Repo/Pix3lify/issues/33.

**Comment by androidacy-user** [comment]
But that not my issue. For them its showing up. For me it is not AT ALL in phone app
________________________________

**Comment by lzlrd** [comment]
@alexa-v2 it says "sometimes load" in the title. So it includes your issue.

**Comment by androidacy-user** [comment]
Mine NEVER loads
________________________________

**Comment by lzlrd** [comment]
@alexa-v2 I'll rephrase that issue - I have an idea why you have this issue but fixing it is delayed under other fixes cause even if it does load we have no way of getting it to work.

**Comment by lazerl0rd** [comment]
@alexa-v2 I'll rephrase that issue - I have an idea why you have this issue but fixing it is delayed under other fixes cause even if it does load we have no way of getting it to work.

**Comment by androidacy-user** [comment]
You posted that twice :-)

**Comment by lzlrd** [comment]
Sorry my bad :P.
